site_name: Facezhuk
docs_dir: .docs
site_url: http://127.0.0.1/mkdocs
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - toc.integrate
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
plugins:
    - search
    - awesome-pages
