"""empty message

Revision ID: 9201cbe9ced7
Revises: 328178ee6889
Create Date: 2022-12-28 14:46:07.334983

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9201cbe9ced7'
down_revision = '328178ee6889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'visited')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.add_column('notification', sa.Column('visited', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
